### ISSUE TITLE
Multi-line input files on Windows OS

### ISSUE THREAD

**Issue by MyrtheW** [seqan/chopper#110]
Chopper curretnly gives an error on multi-line bin files (i.e. this input file consists of multiple lines, referring to multiple sequence files for the different bins), on Windows OS: a carriage return (`\r`) will be read as part of the filename.

**Comment by smehringer** [comment]
Resolved on Gitter. Solution:

Since chopper is currently only supported for unix bases operating systems, the input files have to be created on a unix based system too.

The easiest way, if you have a directory containing files is the following

```
find -type f /path/to/files/ > chopper_input.txt
``` 

And then feed the file `chopper_input.txt` to chopper count.
